=== XiaEmilie/documents-structures/seance_01/xml_livre.dtd
<!--DTD pour des livres-->
<!ELEMENT livres (livre*)>

<!ELEMENT livre (titre,auteur,illustrateur,info_gen,resume)>
	<!ELEMENT titre (#PCDATA)>
	<!ELEMENT auteur (#PCDATA|nom_auteur|prenom_auteur)*>
		<!ELEMENT nom_auteur (#PCDATA)>
		<!ELEMENT prenom_auteur (#PCDATA)>
	<!ELEMENT illustrateur (#PCDATA|nom_illus|prenom_illus)*>
		<!ELEMENT nom_illus (#PCDATA)>
		<!ELEMENT prenom_illus (#PCDATA)>
	<!ELEMENT info_gen (nom_ed,lieu_ed,nb_pages,isbn,annee,code_distributeur,date_parution)>
		<!ELEMENT nom_ed (#PCDATA)>
		<!ELEMENT lieu_ed (#PCDATA)>
		<!ELEMENT nb_pages (#PCDATA)>
		<!ELEMENT isbn (#PCDATA)>
		<!ELEMENT annee (#PCDATA)>
		<!ELEMENT code_distributeur (#PCDATA)>
		<!ELEMENT date_parution (#PCDATA)>
	<!ELEMENT resume (#PCDATA)>

=== XiaEmilie/documents-structures/seance_01/xml_livre.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE livre SYSTEM "xml_livre.dtd">
<livre>
	<titre>Charlie et la chocolaterie</titre>
	<auteur>
		<nom_auteur>Roald</nom_auteur>
		<prenom_auteur>Dahl</prenom_auteur>
	</auteur>
	<illustrateur>
		<nom_illus>Blake</nom_illus>
		<prenom_illus>Quentin</prenom_illus>
	</illustrateur>
	<info_gen>
		<nom_ed>Gallimard Jeunesse</nom_ed>
		<lieu_ed>France</lieu_ed>
		<nb_pages>211</nb_pages>
		<isbn>978-2-07-061263-5</isbn>
		<annee>1964</annee>
		<code_distributeur>A60157</code_distributeur>
		<date_parution>16-06-2016</date_parution>
	</info_gen>
	<resume>
		«Moi, Willy Wonka, j'ai décidé de permettre à cinq enfants de visiter ma chocolaterie cette année. Ces cinq chanceux seront initiés à tous mes secrets, à toute ma magie.» Willy Wonka est le plus grand inventeur de chocolat de tous les temps. Et savez-vous qui est Charlie? Charlie Bucket est le héros de cette histoire. Il y a quatre autres enfants dans ce livre, d'affreux petits garnements, nommés Augustus Gloop (goinfre), Veruca Salt (gâtée), Violette Beauregard (mordue de chewing-gum) et Mike Teavee (obsédé par la télé). Les voilà qui arrivent, avec leurs tickets d'or, à la chocolaterie Wonka! Quels secrets vont-ils découvrir? Notre tournée va commencer! Mais ne vous dispersez pas! Wonka n'aimerait pas perdre l'un de vous à ce stade...
	</resume>
</livre>
